# Generated by Django 3.2.4 on 2021-06-28 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('technology', models.CharField(max_length=50)),
                ('image', models.FilePathField(verbose_name='/img')),
                ('link', models.URLField(max_length=50)),
            ],
        ),
    ]
